# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-25 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_f7', '0002_t_move_go_out_to_other_stac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_move',
            name='count',
            field=models.PositiveIntegerField(default='0', verbose_name='Состоит'),
        ),
    ]
