# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-25 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_f7', '0003_auto_20190325_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_move',
            name='count_finish',
            field=models.PositiveIntegerField(default='0', verbose_name='Состоит всего'),
        ),
        migrations.AlterField(
            model_name='t_move',
            name='count_finish_mother',
            field=models.PositiveIntegerField(default='0', verbose_name='Состоит матерей'),
        ),
        migrations.AlterField(
            model_name='t_move',
            name='count_finish_selo',
            field=models.PositiveIntegerField(default='0', verbose_name='Состоит сельских жителей'),
        ),
        migrations.AlterField(
            model_name='t_move',
            name='death',
            field=models.PositiveIntegerField(default='0', verbose_name='Умерло'),
        ),
        migrations.AlterField(
            model_name='t_move',
            name='go_in_from_ds',
            field=models.PositiveIntegerField(default='0', verbose_name='Пост их ДС'),
        ),
        migrations.AlterField(
            model_name='t_move',
            name='go_in_from_other_stac',
            field=models.PositiveIntegerField(default='0', verbose_name='Переведено из др. стационара'),
        ),
        migrations.AlterField(
            model_name='t_move',
            name='go_in_from_selo',
            field=models.PositiveIntegerField(default='0', verbose_name='Пост из села'),
        ),
        migrations.AlterField(
            model_name='t_move',
            name='go_in_to_17',
            field=models.PositiveIntegerField(default='0', verbose_name='Детей до 17 лет'),
        ),
        migrations.AlterField(
            model_name='t_move',
            name='go_in_to_other_stac',
            field=models.PositiveIntegerField(default='0', verbose_name='Переведено в др. стационар'),
        ),
        migrations.AlterField(
            model_name='t_move',
            name='go_in_up_60',
            field=models.PositiveIntegerField(default='0', verbose_name='Старше 60 лет'),
        ),
        migrations.AlterField(
            model_name='t_move',
            name='go_out',
            field=models.PositiveIntegerField(default='0', verbose_name='Выписано всего'),
        ),
        migrations.AlterField(
            model_name='t_move',
            name='go_out_to_ds',
            field=models.PositiveIntegerField(default='0', verbose_name='Выписано в ДС'),
        ),
        migrations.AlterField(
            model_name='t_move',
            name='go_out_to_other_stac',
            field=models.PositiveIntegerField(default='0', verbose_name='Выписано в др. стационар'),
        ),
        migrations.AlterField(
            model_name='t_move',
            name='goin',
            field=models.PositiveIntegerField(default='0', verbose_name='Поступило всего'),
        ),
    ]
