# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-09 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_f7', '0004_auto_20190325_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_move',
            name='go_in_from_other_stac',
            field=models.PositiveIntegerField(default='0', verbose_name='Переведено из др. отделения'),
        ),
        migrations.AlterField(
            model_name='t_move',
            name='go_in_to_other_stac',
            field=models.PositiveIntegerField(default='0', verbose_name='Переведено в др. отделение'),
        ),
    ]
