# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-11 09:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='s_department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=50, verbose_name='Отделение')),
                ('sort', models.PositiveIntegerField(verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
            },
        ),
        migrations.CreateModel(
            name='s_profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile', models.CharField(blank=True, max_length=50, verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='s_type_pay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_pay', models.CharField(blank=True, max_length=50, verbose_name='Вид оплаты')),
            ],
            options={
                'verbose_name': 'Вид оплаты',
                'verbose_name_plural': 'Виды оплаты',
            },
        ),
        migrations.CreateModel(
            name='s_type_rean',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_rean', models.CharField(blank=True, max_length=50, verbose_name='Вид реанимации')),
            ],
            options={
                'verbose_name': 'Вид реанимации',
                'verbose_name_plural': 'Виды реанимации',
            },
        ),
        migrations.CreateModel(
            name='t_move',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('count', models.PositiveIntegerField(default='0', verbose_name='Состоит')),
                ('goin', models.PositiveIntegerField(default='0', verbose_name='Поступило всего')),
                ('go_in_from_ds', models.PositiveIntegerField(default='0', verbose_name='Пост их ДС')),
                ('go_in_from_selo', models.PositiveIntegerField(default='0', verbose_name='Пост из села')),
                ('go_in_to_17', models.PositiveIntegerField(default='0', verbose_name='Детей до 17 лет')),
                ('go_in_up_60', models.PositiveIntegerField(default='0', verbose_name='Старше 60 лет')),
                ('go_in_from_other_stac', models.PositiveIntegerField(default='0', verbose_name='Переведено из др. отделения')),
                ('go_in_to_other_stac', models.PositiveIntegerField(default='0', verbose_name='Переведено в др. отделение')),
                ('go_out', models.PositiveIntegerField(default='0', verbose_name='Выписано всего')),
                ('go_out_to_other_stac', models.PositiveIntegerField(default='0', verbose_name='Выписано в др. стационар')),
                ('go_out_to_ds', models.PositiveIntegerField(default='0', verbose_name='Выписано в ДС')),
                ('death', models.PositiveIntegerField(default='0', verbose_name='Умерло')),
                ('count_finish', models.PositiveIntegerField(default='0', verbose_name='Состоит всего')),
                ('count_finish_selo', models.PositiveIntegerField(default='0', verbose_name='Состоит сельских жителей')),
                ('count_finish_mother', models.PositiveIntegerField(default='0', verbose_name='Состоит матерей')),
                ('Add', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_f7.s_department', verbose_name='Отделение')),
                ('type_pay', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_f7.s_type_pay', verbose_name='Вид оплаты')),
                ('type_rean', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_f7.s_type_rean', verbose_name='Вид реанимации')),
            ],
            options={
                'verbose_name': 'Движение',
                'verbose_name_plural': 'Движения',
            },
        ),
        migrations.AddField(
            model_name='s_department',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_f7.s_profile', verbose_name='Профиль'),
        ),
    ]
